### ISSUE TITLE
Line chart wrongly presented in Y-axis when chosing X-axis data as numeric

### ISSUE THREAD

**Issue by vanducng** [tcd1nc/PowerBI-Control-Chart#8]
When chosing X-axis data as numeric, the line chart display vertically. Can you pls help to take a look on this. Thanks.
![2018-10-07_15h23_48](https://user-images.githubusercontent.com/2980905/46579977-8f44b900-ca45-11e8-9fc1-b7a9c50f0857.png)

**Comment by tcd1nc** [comment]
Are x-axis values sorted in ascending order?

**Comment by vanducng** [comment]
> Are x-axis values sorted in ascending order?

No, i dont think so.
